sonar.projectKey=overcode250204_openalex
sonar.organization=overcode250204

sonar.sources=lib
sonar.tests=test

sonar.exclusions=**/*.g.dart,**/*.freezed.dart

sonar.dart.lcov.reportPaths=coverage/lcov.info