// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4z-nOORZNHfFqCGnvrYCzCnaKX_NSgY',
    appId: '1:489601979984:web:0bc8ce715baedebc19a355',
    messagingSenderId: '489601979984',
    projectId: 'openalex-34f8f',
    authDomain: 'openalex-34f8f.firebaseapp.com',
    storageBucket: 'openalex-34f8f.firebasestorage.app',
    measurementId: 'G-C4G798XKT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7nq-zBftPY47xGKv6xqjSIB1hfKcGcs',
    appId: '1:489601979984:android:b3c8eeb15fd8b80919a355',
    messagingSenderId: '489601979984',
    projectId: 'openalex-34f8f',
    storageBucket: 'openalex-34f8f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0_IB6KA-IYDrdqJ1VAuVErIIAmJqXfk',
    appId: '1:489601979984:ios:f9686b54e9d2e95e19a355',
    messagingSenderId: '489601979984',
    projectId: 'openalex-34f8f',
    storageBucket: 'openalex-34f8f.firebasestorage.app',
    androidClientId:
        '489601979984-62mu6ri1ij6k8bhdvkkv01n2d9sipa8p.apps.googleusercontent.com',
    iosClientId:
        '489601979984-ke3v643g3gflp57h52okp6i0vt21a2h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.openalex',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb0_IB6KA-IYDrdqJ1VAuVErIIAmJqXfk',
    appId: '1:489601979984:ios:f9686b54e9d2e95e19a355',
    messagingSenderId: '489601979984',
    projectId: 'openalex-34f8f',
    storageBucket: 'openalex-34f8f.firebasestorage.app',
    androidClientId:
        '489601979984-62mu6ri1ij6k8bhdvkkv01n2d9sipa8p.apps.googleusercontent.com',
    iosClientId:
        '489601979984-ke3v643g3gflp57h52okp6i0vt21a2h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.openalex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4z-nOORZNHfFqCGnvrYCzCnaKX_NSgY',
    appId: '1:489601979984:web:54fd6f729c5cd16c19a355',
    messagingSenderId: '489601979984',
    projectId: 'openalex-34f8f',
    authDomain: 'openalex-34f8f.firebaseapp.com',
    storageBucket: 'openalex-34f8f.firebasestorage.app',
    measurementId: 'G-S690C2SVRC',
  );
}
