// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT39IKn9DMlkZ_CF98Kig9Moh7vyAzpkY',
    appId: '1:487010272344:web:5e942fb5ea1cf92c1a362d',
    messagingSenderId: '487010272344',
    projectId: 'openalex-asm',
    authDomain: 'openalex-asm.firebaseapp.com',
    storageBucket: 'openalex-asm.firebasestorage.app',
    measurementId: 'G-MMKVBFB443',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcsI40yfulXH_ls3DacmMdP62Ifq-Y4c',
    appId: '1:487010272344:android:35366332f6a114441a362d',
    messagingSenderId: '487010272344',
    projectId: 'openalex-asm',
    storageBucket: 'openalex-asm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcnuUhXIDkaKxoJmjzT7yeXf_zmzkQav8',
    appId: '1:487010272344:ios:1e3a520268152d081a362d',
    messagingSenderId: '487010272344',
    projectId: 'openalex-asm',
    storageBucket: 'openalex-asm.firebasestorage.app',
    androidClientId: '487010272344-spmp1j6gbrs6qvak67a5q2ov54fnjfhf.apps.googleusercontent.com',
    iosClientId: '487010272344-7m7g9oc8bdftp0ou64nrl178ualvq284.apps.googleusercontent.com',
    iosBundleId: 'com.example.openalex',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcnuUhXIDkaKxoJmjzT7yeXf_zmzkQav8',
    appId: '1:487010272344:ios:1e3a520268152d081a362d',
    messagingSenderId: '487010272344',
    projectId: 'openalex-asm',
    storageBucket: 'openalex-asm.firebasestorage.app',
    androidClientId: '487010272344-spmp1j6gbrs6qvak67a5q2ov54fnjfhf.apps.googleusercontent.com',
    iosClientId: '487010272344-7m7g9oc8bdftp0ou64nrl178ualvq284.apps.googleusercontent.com',
    iosBundleId: 'com.example.openalex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT39IKn9DMlkZ_CF98Kig9Moh7vyAzpkY',
    appId: '1:487010272344:web:af68811496f912b91a362d',
    messagingSenderId: '487010272344',
    projectId: 'openalex-asm',
    authDomain: 'openalex-asm.firebaseapp.com',
    storageBucket: 'openalex-asm.firebasestorage.app',
    measurementId: 'G-ZXEZCL7E41',
  );
}
