import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:openalex/models/auth/app_user.dart';
import 'package:openalex/models/report/report_upload_result.dart';
import 'package:openalex/models/report/uploaded_report.dart';
import 'package:openalex/models/trend/trend_report_snapshot.dart';
import 'package:openalex/services/analytics/app_analytics_service.dart';
import 'package:openalex/services/pdf_export_service.dart';
import 'package:openalex/services/pdf_report_layout_service.dart';
import 'package:openalex/services/report/report_metadata_service.dart';
import 'package:openalex/services/report/report_storage_service.dart';
import 'package:openalex/services/trend_report_export_service.dart';
import 'package:openalex/viewmodels/dashboard_view_model.dart';

void main() {
  group('DashboardViewModel', () {
    test('exposes loading state while exporting dashboard PDF', () async {
      final completer = Completer<PdfExportResult>();
      final viewModel = DashboardViewModel(
        exportService: const TrendReportExportService(),
        pdfExportService: _ControlledPdfExportService(completer),
        reportStorageService: _RecordingReportStorageService(),
      );

      final exportFuture = viewModel.exportDashboardPdfReport(_emptyReport());

      expect(viewModel.isExporting, isTrue);

      completer.complete(
        PdfExportResult(
          file: File('dashboard.pdf'),
          bytes: Uint8List.fromList([1, 2, 3]),
          byteLength: 128,
          generatedAt: DateTime(2026, 6, 25),
        ),
      );
      final result = await exportFuture;

      expect(result.file.path, 'dashboard.pdf');
      expect(viewModel.isExporting, isFalse);
    });

    test('resets loading state when dashboard PDF export fails', () async {
      final completer = Completer<PdfExportResult>();
      final viewModel = DashboardViewModel(
        exportService: const TrendReportExportService(),
        pdfExportService: _ControlledPdfExportService(completer),
        reportStorageService: _RecordingReportStorageService(),
      );

      final exportFuture = viewModel.exportDashboardPdfReport(_emptyReport());

      expect(viewModel.isExporting, isTrue);

      completer.completeError(Exception('disk full'));

      await expectLater(exportFuture, throwsException);
      expect(viewModel.isExporting, isFalse);
    });

    test('exports dashboard PDF and uploads generated bytes', () async {
      final tempDirectory = await Directory.systemTemp.createTemp(
        'dashboard-upload-test',
      );
      addTearDown(() => tempDirectory.delete(recursive: true));
      final reportFile = File('${tempDirectory.path}/dashboard.pdf');
      final reportBytes = Uint8List.fromList([1, 2, 3]);
      await reportFile.writeAsBytes(reportBytes);
      final storageService = _RecordingReportStorageService();
      final metadataService = _RecordingReportMetadataService();
      final viewModel = DashboardViewModel(
        exportService: const TrendReportExportService(),
        pdfExportService: _ImmediatePdfExportService(reportFile),
        reportStorageService: storageService,
        reportMetadataService: metadataService,
        currentUserIdResolver: () => 'user-1',
      );

      final result = await viewModel.exportAndUploadDashboardPdfReport(
        _emptyReport(),
      );

      expect(storageService.lastBytes, reportBytes);
      expect(storageService.lastFileName, 'dashboard.pdf');
      expect(storageService.lastContentType, 'application/pdf');
      expect(storageService.lastTopic, 'AI');
      expect(metadataService.saveCount, 1);
      expect(metadataService.lastTopic, 'AI');
      expect(metadataService.lastUserId, 'user-1');
      expect(
        metadataService.lastUploadResult?.downloadUrl,
        'https://cdn.test/dashboard.pdf',
      );
      expect(result.uploadResult.downloadUrl, 'https://cdn.test/dashboard.pdf');
      expect(
        viewModel.lastUploadedPdfReport?.downloadUrl,
        'https://cdn.test/dashboard.pdf',
      );
      expect(viewModel.isExporting, isFalse);

      viewModel.clearUploadedPdfReport();

      expect(viewModel.lastUploadedPdfReport, isNull);
    });

    test('logs pdf export analytics after upload metadata is saved', () async {
      final tempDirectory = await Directory.systemTemp.createTemp(
        'dashboard-analytics-test',
      );
      addTearDown(() => tempDirectory.delete(recursive: true));
      final reportFile = File('${tempDirectory.path}/dashboard.pdf');
      await reportFile.writeAsBytes(Uint8List.fromList([1, 2, 3]));
      final analytics = _RecordingPdfExportAnalyticsService();
      final viewModel = DashboardViewModel(
        exportService: const TrendReportExportService(),
        pdfExportService: _ImmediatePdfExportService(reportFile),
        reportStorageService: _RecordingReportStorageService(),
        reportMetadataService: _RecordingReportMetadataService(),
        analyticsService: analytics,
      );

      await viewModel.exportAndUploadDashboardPdfReport(_emptyReport());

      expect(analytics.pdfExportEvents, hasLength(1));
      expect(analytics.pdfExportEvents.single, {
        'topic': 'AI',
        'exportType': 'dashboard_pdf',
        'provider': 'fake',
        'bucket': 'reports',
        'fileName': 'dashboard.pdf',
        'sizeBytes': 3,
        'hasUploadedLink': 1,
      });
    });

    test(
      'does not log pdf export analytics when metadata save fails',
      () async {
        final tempDirectory = await Directory.systemTemp.createTemp(
          'dashboard-analytics-failure-test',
        );
        addTearDown(() => tempDirectory.delete(recursive: true));
        final reportFile = File('${tempDirectory.path}/dashboard.pdf');
        await reportFile.writeAsBytes(Uint8List.fromList([1, 2, 3]));
        final analytics = _RecordingPdfExportAnalyticsService();
        final viewModel = DashboardViewModel(
          exportService: const TrendReportExportService(),
          pdfExportService: _ImmediatePdfExportService(reportFile),
          reportStorageService: _RecordingReportStorageService(),
          reportMetadataService: _FailingReportMetadataService(),
          analyticsService: analytics,
        );

        await expectLater(
          viewModel.exportAndUploadDashboardPdfReport(_emptyReport()),
          throwsException,
        );

        expect(analytics.pdfExportEvents, isEmpty);
        expect(viewModel.isExporting, isFalse);
      },
    );

    test('keeps export success when analytics logging fails', () async {
      final tempDirectory = await Directory.systemTemp.createTemp(
        'dashboard-analytics-throws-test',
      );
      addTearDown(() => tempDirectory.delete(recursive: true));
      final reportFile = File('${tempDirectory.path}/dashboard.pdf');
      await reportFile.writeAsBytes(Uint8List.fromList([1, 2, 3]));
      final viewModel = DashboardViewModel(
        exportService: const TrendReportExportService(),
        pdfExportService: _ImmediatePdfExportService(reportFile),
        reportStorageService: _RecordingReportStorageService(),
        reportMetadataService: _RecordingReportMetadataService(),
        analyticsService: _ThrowingAnalyticsService(),
      );

      final result = await viewModel.exportAndUploadDashboardPdfReport(
        _emptyReport(),
      );

      expect(result.uploadResult.downloadUrl, 'https://cdn.test/dashboard.pdf');
      expect(viewModel.isExporting, isFalse);
    });
  });
}

class _ControlledPdfExportService extends PdfExportService {
  final Completer<PdfExportResult> _completer;

  _ControlledPdfExportService(this._completer)
    : super(layoutService: const PdfReportLayoutService());

  @override
  Future<PdfExportResult> exportDashboardPdfReport(
    TrendReportSnapshot report, {
    DateTime? generatedAt,
  }) {
    return _completer.future;
  }
}

class _ImmediatePdfExportService extends PdfExportService {
  final File _file;

  _ImmediatePdfExportService(this._file)
    : super(layoutService: const PdfReportLayoutService());

  @override
  Future<PdfExportResult> exportDashboardPdfReport(
    TrendReportSnapshot report, {
    DateTime? generatedAt,
  }) async {
    return PdfExportResult(
      file: _file,
      bytes: await _file.readAsBytes(),
      byteLength: await _file.length(),
      generatedAt: generatedAt ?? DateTime.utc(2026, 6, 25, 9),
    );
  }
}

class _RecordingReportStorageService implements ReportStorageService {
  Uint8List? lastBytes;
  String? lastFileName;
  String? lastContentType;
  String? lastTopic;
  DateTime? lastUploadedAt;

  @override
  Future<ReportUploadResult> uploadReport({
    required Uint8List bytes,
    required String fileName,
    required String contentType,
    required String topic,
    DateTime? uploadedAt,
  }) async {
    lastBytes = bytes;
    lastFileName = fileName;
    lastContentType = contentType;
    lastTopic = topic;
    lastUploadedAt = uploadedAt;

    return ReportUploadResult(
      provider: 'fake',
      bucket: 'reports',
      objectKey: 'reports/$fileName',
      fileName: fileName,
      downloadUrl: 'https://cdn.test/$fileName',
      sizeBytes: bytes.length,
      uploadedAt: uploadedAt ?? DateTime.utc(2026, 6, 25),
    );
  }
}

class _RecordingReportMetadataService implements ReportMetadataService {
  int saveCount = 0;
  ReportUploadResult? lastUploadResult;
  String? lastTopic;
  String? lastUserId;

  @override
  Future<void> saveUploadedReport({
    required ReportUploadResult uploadResult,
    required String topic,
    String? userId,
  }) async {
    saveCount++;
    lastUploadResult = uploadResult;
    lastTopic = topic;
    lastUserId = userId;
  }

  @override
  Future<List<UploadedReport>> fetchUploadedReports({
    required String userId,
    int limit = 20,
  }) async {
    return const [];
  }
}

class _FailingReportMetadataService implements ReportMetadataService {
  @override
  Future<void> saveUploadedReport({
    required ReportUploadResult uploadResult,
    required String topic,
    String? userId,
  }) async {
    throw Exception('metadata unavailable');
  }

  @override
  Future<List<UploadedReport>> fetchUploadedReports({
    required String userId,
    int limit = 20,
  }) async {
    return const [];
  }
}

class _RecordingPdfExportAnalyticsService implements AppAnalyticsService {
  final pdfExportEvents = <Map<String, Object?>>[];

  @override
  Future<void> clearUser() async {}

  @override
  Future<void> logLogin({
    required AppUser user,
    required String method,
  }) async {}

  @override
  Future<void> logLogout({
    required AppUser? user,
    required String method,
  }) async {}

  @override
  Future<void> logSearchTopic(
    String keyword, {
    int? resultCount,
    String? searchSource,
    String? topicId,
    int? hasValidTopic,
    int? filterYearFrom,
    int? filterYearTo,
    int? openAccessOnly,
    String? sortOption,
  }) async {}

  @override
  Future<void> logViewKeyword({required String keyword}) async {}

  @override
  Future<void> logViewPublication({
    required String publicationTitle,
    required int? publicationYear,
  }) async {}

  @override
  Future<void> logPdfExport({
    required String topic,
    required String exportType,
    required String provider,
    required String bucket,
    required String fileName,
    required int sizeBytes,
    required int hasUploadedLink,
  }) async {
    pdfExportEvents.add({
      'topic': topic,
      'exportType': exportType,
      'provider': provider,
      'bucket': bucket,
      'fileName': fileName,
      'sizeBytes': sizeBytes,
      'hasUploadedLink': hasUploadedLink,
    });
  }
}

class _ThrowingAnalyticsService extends _RecordingPdfExportAnalyticsService {
  @override
  Future<void> logPdfExport({
    required String topic,
    required String exportType,
    required String provider,
    required String bucket,
    required String fileName,
    required int sizeBytes,
    required int hasUploadedLink,
  }) async {
    throw Exception('analytics unavailable');
  }
}

TrendReportSnapshot _emptyReport() {
  return const TrendReportSnapshot(
    topic: 'AI',
    publications: [],
    publicationCountByYear: {},
    topInfluentialPapers: [],
    topJournals: {},
    topAuthors: {},
    totalPublications: 0,
    averageCitationCount: 0,
    mostActiveYear: null,
    topJournal: null,
    topAuthor: null,
    mostInfluentialPaper: null,
  );
}
